### ISSUE TITLE
コードレビュー#1

### ISSUE THREAD

**Issue by yamataku29** [Tshi66/PFpractice#11]
下記にレビューコメントを入れたので、後ほど修正対応をしてみてください🙆‍♂️

# TODO
- [x] https://github.com/Tshi66/PFpractice/commit/f9464267827fda47769c404f015d604180e1bff5#r36967869
- [x] https://github.com/Tshi66/PFpractice/commit/f9464267827fda47769c404f015d604180e1bff5#r36967887
- [x] https://github.com/Tshi66/PFpractice/commit/f9464267827fda47769c404f015d604180e1bff5#r36967899
- [x] https://github.com/Tshi66/PFpractice/commit/f9464267827fda47769c404f015d604180e1bff5#r36967931
- [x] https://github.com/Tshi66/PFpractice/commit/0a470a2f27d74355164b3339267b8186fa7dc675#r36967936
- [x] https://github.com/Tshi66/PFpractice/commit/0a470a2f27d74355164b3339267b8186fa7dc675#r36967942
- [x] https://github.com/Tshi66/PFpractice/commit/8ad0a562d78c36f582828c2e894c64a7f7c76775#r36967959
- [x] https://github.com/Tshi66/PFpractice/commit/8ad0a562d78c36f582828c2e894c64a7f7c76775#r36967961
